spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-services?useSSL=false
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: user-services
server:
  port: 9001

eureka:
  instance:
    hostname: localhost