server:
  port: 9000
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-services
          predicates:
            - Path=/student/**
        - id: course-service
          uri: lb://course-services
          predicates:
            - Path=/course/**, /department/**